Apparmor config files are only copied if restart option is set
    - Missed additional check in else statement
    - Removed check for restart option and copy the files regardless.
    Without the restart option and these f apparmor files the following
    error is encountered trying to start up the containers:
    Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused "apparmor failed to apply profile: write /proc/self/attr/exec: no such file or directory"": unknown
    Error: failed to start containers: c471a3aa0dae